### ISSUE TITLE
Capital U is now not working! Thinks this works before.

### ISSUE THREAD

**Issue by wikrie** [rbatinov/mssql-extensions-starter-pack#2]
Capital U is now not working! Thinks this works before.

**Comment by rbatinov** [comment]
UPDATE: Note that Captial U was not updated at all in version 0.3.0. After your new comment, I noticed that Captial U didn't work BEFORE the 0.3.0 update as well.

So I removed the shortcut with the U letter and now ALL the letters U, C, I, and D work fine! (version 0.4.0)

Cheers,

RB Projects.

-----------------------------------------------
